### ISSUE TITLE
PyCharm Configuration Instructions

### ISSUE THREAD

**Issue by myhndl** [polyswarm/documentation#104]
It would be good to include instructions on setting up a proper PyCharm environment for development.

Some items:
* for `polyswarm-client`, configure PyCharm's root source directory to be `polyswarm-client/src`

**Comment by mjkoo** [comment]
More context on sources root issue, this is true for most/all our python packages due to us using a `src/` subdirectory, so pycharm needs to know to look for packages there (there can be more than one "root source" directory so above description is slightly misleading).

src/ directory structure is set up as recommended for pytest/tox.

**Comment by mrtizmoatwork** [comment]
I have the required steps here.. but don't have time to make them into a proper documentation page.


1. Download and Install pycharm community edition - https://www.jetbrains.com/pycharm/download
2. Start pycharm
3. File -> Open
4. select the microengine directory that was created from engine-template
5. In the left menu, right-click on the `src` dir and select `Mark Directory as`, then select `Sources Root`
6. Go to File -> Settings -> Project -> Project Interpreter
- In the right frame, click the gear icon to the right of the project interpreter box.
- Select Add
- Click `Existing environment`
- Specify the `polyswarmvenv` virtual environment that you made during the development environment setup.
- Click Ok, and Ok.
7. If prompted to Install requirements, do so.

You should now have a pycharm environment that has the necessary minimum functionality for microengine development.
